#!/usr/bin/env bash
# This script do a ping to an adresse IP passed in args.

#check if an arg have been gived.
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi
#a ping to the IP adress gived.
ping -c 5 "$1"
