#!/usr/bin/env bash
# This script modifies /etc/hosts to change the localhost IP and set facebook.com to 8.8.8.8

echo -e "127.0.0.2\tlocalhost" > /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
