#!/usr/bin/env bash
# Script to change localhost and facebook.com IP addresses

# Modify the /etc/hosts file to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i '/127.0.0.1/c\127.0.0.2 localhost' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
